[environments.mint]
store = "korean-skincare-uk"
theme = "186130530684"
theme-editor-sync = true
ignore = "*.json"

[environments.mint1]
store = "korean-skincare-uk"
theme = "186188562812"
theme-editor-sync = true
ignore = "*.json"

[environments.qmcar]
store = "qmcar"
theme = "185698910510"
theme-editor-sync = true
ignore = "*.json"

[environments.test]
store = "korean-skincare-uk"
theme = "186343391612"
theme-editor-sync = true
ignore = "*.json"

